name: charts_common
version: 0.13.0
description: A common library for charting packages.
homepage: https://github.com/google/charts

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: ">=3.35.0"

dependencies:
  collection: ^1.19.1
  intl: ^0.20.2
  logging: ^1.3.0
  meta: ^1.16.0
  vector_math: ^2.2.0

dev_dependencies:
  mockito: ^5.5.1
  test: ^1.26.3
