name: charts_flutter
version: 0.13.0
publish_to: none
description: Material Design charting library for flutter.
homepage: https://github.com/google/charts

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: ">=3.35.0"

dependencies:
  # Pointing this to a local path allows for pointing to the latest code
  # in Github for open source development.
  #
  # The pub version of charts_flutter will point to the pub version of charts_common.
  # The latest pub version is commented out and shown below as an example.
  # charts_common: ^0.12.0
  # charts_common:
  # path: ../charts_common/
  # INFO: This modification is necessary to use our modified charts_common
  charts_common:
    git:
      url: git@github.com:Andre-lbc/charts.git
      path: charts_common
  collection: ^1.18.0
  flutter:
    sdk: flutter
  intl: ^0.20.2
  logging: ^1.2.0
  meta: ^1.16.0


dev_dependencies:
  mockito: ^5.4.4
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  test: ^1.24.9
